# nixpacks.toml
# Konfigurasi eksplisit untuk Nixpacks agar mengenali Python dan Node.js

packages = ["nodejs", "python3" ] 

[phases.setup]
# Perintah setup yang dijalankan untuk menginstal dependensi
# Ini akan dijalankan sebelum build atau start commands
commands = [
    # Cek apakah pip sudah ada, jika tidak, unduh dan instal
    "if ! python3 -c \"import pip\" &> /dev/null; then curl -sS https://bootstrap.pypa.io/get-pip.py | python3; fi",
    "python3 -m pip install -r requirements.txt", # Sekarang ini seharusnya berfungsi
    "cd trapesium-frontend && npm install --no-fund --no-audit && cd ..",
]

[phases.build]
# Perintah build yang dijalankan setelah setup
commands = [
    "cd trapesium-frontend && npm run build && cd ..",
    "python3 -m manage.py collectstatic --noinput", 
]

[start]
# Perintah untuk memulai aplikasi
cmd = "gunicorn metnumtrapesium.wsgi:application --bind 0.0.0.0:$PORT"

[environments]
# Variabel lingkungan yang diperlukan
# Pastikan DJANGO_SETTINGS_MODULE diatur jika tidak di manage.py
DJANGO_SETTINGS_MODULE = "metnumtrapesium.settings"

# Atur PORT sesuai standar Railway
PORT = "$PORT"

# Jika Anda perlu variabel DB_URL
# DATABASE_URL = "$DATABASE_URL"
