[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'nodejs_20', 'nodePackages.npm']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'cd trapesium-frontend && npm ci --only=production'
]

[phases.build]
cmds = [
  'cd trapesium-frontend && npm run build'
]
