[phases.setup]
nixPkgs = ['python312', 'nodejs_18', 'nodePackages.npm']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'python -m pip install -r requirements.txt',
  'cd trapesium-frontend && npm ci --only=production'
]

[phases.build]
cmds = [
  'cd trapesium-frontend && npm run build'
]

[start]
cmd = 'python manage.py runserver 0.0.0.0:$PORT'
