# nixpacks.toml

packages = ["nodejs-22_x", "python3"]

[phases.setup]
commands = [
    "python3 -m venv .venv",
    ". .venv/bin/activate && pip install --upgrade pip",
    ". .venv/bin/activate && pip install -r requirements.txt",
    # PERUBAHAN DI SINI: Panggil script baru
    "bash trapesium-frontend/build_frontend.sh",
]

[phases.build]
commands = [
    # PERUBAHAN DI SINI: Hapus perintah npm build, sudah dipindahkan ke script
    ". .venv/bin/activate && python manage.py collectstatic --noinput",
]

[start]
cmd = ". .venv/bin/activate && gunicorn metnumtrapesium.wsgi:application --bind 0.0.0.0:$PORT"

[environments]
DJANGO_SETTINGS_MODULE = "metnumtrapesium.settings"
PORT = "$PORT"
