# nixpacks.toml
[phases.setup]
nixPkgs = ['python312', 'nodejs_22', 'nodePackages.npm']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'cd trapesium-frontend && npm ci --only=production'
]

[phases.build]
cmds = [
  'cd trapesium-frontend && npm run build',
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py runserver 0.0.0.0:$PORT'
