[phases.setup]
nixPkgs = ['python11', 'nodejs_20']

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd trapesium-frontend && npm ci --only=production'
]

[start]
cmd = '. /opt/venv/bin/activate && python app.py'
